# IMPORT

In [1]:
import tempfile
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score, roc_curve
from sklearn.pipeline import Pipeline

# LOAD DATA, TRAIN MODEL

In [2]:
%%bash

if [ ! -d ./data ]; then
    mkdir ./data
fi

if [ ! -f ./data/trainingandtestdata.zip ]; then
    wget -q -O ./data/trainingandtestdata.zip http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip
fi

unzip -n ./data/trainingandtestdata.zip -d ./data

Archive:  ./data/trainingandtestdata.zip


In [3]:
columns = ['polarity', 'tweetid', 'date', 'query_name', 'user', 'text']
df_train_file_path = './data/training.1600000.processed.noemoticon.csv'
df_train_name = 'training.1600000.processed.noemoticon'
df_train = pd.read_csv(df_train_file_path,
                      header=None,
                      encoding='ISO-8859-1')

df_test_file_path = './data/testdata.manual.2009.06.14.csv'
df_test_name = 'testdata.manual.2009.06.14'
df_test = pd.read_csv(df_test_file_path,
                     header=None,
                     encoding='ISO-8859-1')
df_train.columns = columns
df_test.columns = columns
df_train.shape[0]

1600000

In [4]:
sentiment_lr = Pipeline([
                         ('count_vect', CountVectorizer(min_df=100,
                                                        ngram_range=(1,2),
                                                        stop_words='english')), 
                         ('lr', LogisticRegression())])
sentiment_lr.fit(df_train.text, df_train.polarity)

/Users/rishabramanathan/opt/miniconda3/envs/unbox_demo/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Pipeline(steps=[('count_vect',
                 CountVectorizer(min_df=100, ngram_range=(1, 2),
                                 stop_words='english')),
                ('lr', LogisticRegression())])

In [5]:
x_test, y_test = df_test.text[df_test.polarity != 2], df_test.polarity[df_test.polarity != 2]
print(classification_report(y_test, sentiment_lr.predict(x_test)))

              precision    recall  f1-score   support

           0       0.87      0.82      0.84       177
           4       0.83      0.88      0.86       182

    accuracy                           0.85       359
   macro avg       0.85      0.85      0.85       359
weighted avg       0.85      0.85      0.85       359



In [6]:
sentiment_lr.predict([x_test[0]])

array([4])

In [7]:
sentiment_lr.predict(['good', 'bad'])

array([4, 0])

# UNBOX

In [8]:
import unboxapi
client = unboxapi.UnboxClient(email="me@vikasnair.com", password="00000000")

## Create function

In [9]:
# class_dict = { 4: 'positive', 2: 'neutral', 0: 'negative'}
class_names = ['negative', 'positive']
dataset_labels = [0, 4]
def predict_function(model, text_list):
    return model.predict_proba(text_list), class_names, dataset_labels

In [10]:
texts = ['some new text, sweet noodles', 'happy time', 'sad day']

predict_function(sentiment_lr, texts)

(array([[0.15715401, 0.84284599],
        [0.20192416, 0.79807584],
        [0.97165564, 0.02834436]]),
 ['negative', 'positive'],
 [0, 4])

# Package (function, model) & Upload to Firebase

In [14]:
print('Uploading model...')
client.add_model(function=predict_function, 
                 model=sentiment_lr, 
                 name='03.15.2021.sentiment_analyzer',
                 description='this is my sklearn sentiment model')
print('Complete.')

Uploading model...
[2021-03-20 13:32:17,428] WARNING - pip package requirement scikit-learn already exist
Complete.


In [ ]:
print('\nUploading dataset (from file)...')
with tempfile.TemporaryDirectory() as tmpdir:
    df_train.to_csv(f'{tmpdir}/dataset.csv')
    response_i = client.add_dataset(file_path=f'{tmpdir}/dataset.csv', 
                                    name=df_train_name, 
                                    description='this is my sentiment train dataset',
                                    label_column_name='polarity',
                                    text_column_name='text')
print(f'Complete. Response: {response_i}')

In [ ]:
print('\nUploading dataset (from data frame)...')
response_j = client.add_dataframe(df=df_test, 
                                  name=df_test_name, 
                                  description='this is my sentiment test dataset',
                                  label_column_name='polarity',
                                  text_column_name='text')
print(f'Complete. Response: {response_j}')

# Internal Tests

In [ ]:
from requests import get, post
import unboxapi
client = unboxapi.UnboxClient(email="me@vikasnair.com", password="00000000")

In [ ]:
# dataset/download_rows
payload = {
    "datasetId": "88b5158e-8858-11eb-8d52-1e008a21a079",
    "offset": 0,
    "limit": 3,
#     "indices": [1, 2, 3],
}
response = get('http://0.0.0.0:8080/api/dataset/download_rows', headers={"Authorization": client.firebase_api.user["idToken"]}, json=payload)
response.content

In [ ]:
# dataset/add_tag
payload = {
    "datasetId": "88b5158e-8858-11eb-8d52-1e008a21a079",
    "tagName": "test",
    "indices": [1, 2],
}
response = post('http://0.0.0.0:8080/api/dataset/add_tag', headers={"Authorization": client.firebase_api.user["idToken"]}, json=payload)
response.content

In [ ]:
# run/create_run_report
payload = {
    "datasetId": "88b5158e-8858-11eb-8d52-1e008a21a079",
    "modelId": "4d8bd12e-8622-11eb-a9d7-1e008a21a079",
}
response = post('http://0.0.0.0:8080/api/run/create_run_report', headers={"Authorization": client.firebase_api.user["idToken"]}, json=payload)
response.content

In [ ]:
# run/download_run_rows
payload = {
    "runReportId": "a2a00ad0-8858-11eb-b2d7-1e008a21a079",
#     "offset": 0,
#     "limit": 3,
    "indices": [1, 2, 3],
}
response = get('http://0.0.0.0:8080/api/run/download_rows', headers={"Authorization": client.firebase_api.user["idToken"]}, json=payload)
response.content

In [ ]:
# Test error analysis / dataset-model association
result = client._test_associate(model_id='', 
                                dataset_id='62f26430-845e-11eb-a9b2-1e008a21a079',
                                user_id='ytGD2XvoGPSaippqWhAmi5V8mHT2')
print(result.content)

In [ ]:
# Test checklist invariance test
test_config = {'testType': 'inv', 'examplesPerRow': 3, 'perturbationMode': 'change_names'}

result = client._test_add_test_suite(run_id='', 
                                     user_id='ytGD2XvoGPSaippqWhAmi5V8mHT2',
                                     test_config=test_config)
print(result.content)